### ISSUE TITLE
pynag service.get_effective_command_line() doesn't substitute values for user attributes that are in lowercase

### ISSUE THREAD

**Issue by wasserman** [pynag/pynag#202]
When a host user attribute is in lowercase then pynag doesn't substitute the value unless it is in caps.
So if there is a host variable called `_port`, then the `$_HOSTPORT$` gets turned into `_PORT` at 
[pynag 0.9.1 L1256](https://github.com/pynag/pynag/blob/3eb5818cfb0fd902e6317498f74377c243fa62a3/pynag/Model/__init__.py#L1257).

This line can be probably be changed to force lowercase, as is done with [L1264](https://github.com/pynag/pynag/blob/3eb5818cfb0fd902e6317498f74377c243fa62a3/pynag/Model/__init__.py#L1257):

> return self["_%s" % name.lower()]

Since I don't know the impacts, a safer way is:

> return self["_%s" % name] or self["_%s" % name.lower()]

I initially found this problem via Adagios, where the command line doesn't display user attributes when they are defined in lowercase.  This fixes that too!  :)

**Comment by peternewman** [comment]
Can I just check that although this is in [pynag-0.9.1-1_](https://github.com/pynag/pynag/releases/tag/pynag-0.9.1-1_) it wasn't in the 0.9.1+dfsg-1 type releases in Debian/Ubuntu?
