### ISSUE TITLE
Parsing multiple hostgroups is broken

### ISSUE THREAD

**Issue by oranki** [pynag/pynag#210]
When host definition has multiple hostgroups, pynag fails parsing them.

Works:

```
define host {
  ...
  hostgroups group1
} 
```

`% pynag list host_name where hostgroups=group1`

Doesn't work:

```
define host {
  ...
  hostgroups group1, group2
} 
```

`% pynag list host_name where hostgroups=group1`

Same problem can be reproduced also with Python, eg.

```
>>> import pynag
>>> pynag.Model.Host.objects.filter(hostgroups="group1")
```

**Comment by palli** [comment]
This is intended, as using hostgroups="group1" will search only for exact match.

Try doing this instead:
```
pynag list host_name where hostgroups__contains=group1
```

Same in python code:
```
>>> import pynag
>>> pynag.Model.Host.objects.filter(hostgroups__contains="group1")
```

**Comment by pall-valmundsson** [comment]
Or even `hostgroups__in=group1`.

@palli, is documentation lacking for the filters?

**Comment by oranki** [comment]
Thanks. The filter syntax documentation is indeed a bit suboptimal; it's hard to find and contains only arbitrary examples instead of full syntax reference. What ultimately threw me off was probably the example on github readme:

> Create a new ssh service check for every host in the unix hostgroup:

`hosts = pynag.Model.Host.objects.filter(hostgroup="unixservers")`

It would also help if documentation link was available first thing on http://pynag.org rather than halfway through the github readme.

Anyway, thanks for creating and maintaining pynag, it's been very useful!

**Comment by wangdepeng** [comment]
@palli No document for filters. Can you help add it? Thanks.

**Comment by wangdepeng** [comment]
@palli One more question, I want to exclude several groups in the where condition.
pynag list host_name where hostgroups__nocontains=["group1","group"]
This seems to be not working.

**Comment by toddejohnson** [comment]
I think this is just documentation missing.  __in works great!
