### ISSUE TITLE
Github/PyPI releases

### ISSUE THREAD

**Issue by omron93** [pynag/pynag#261]
Hi,
please create github releases for latest pynag versions and upload them to pypi. 

Latest pynag version on pypi is 0.9.1 from year 2014.

Thanks

**Comment by omron93** [comment]
@gardart @palli @tomas-edwardsson Who can create a new releases? (asking you, because only you've made a new pynag release)

**Comment by gardart** [comment]
Hi @omron93 , I will create a new release very soon and upload to Pypi. Sorry for the delay!
