### ISSUE TITLE
No rename for services

### ISSUE THREAD

**Issue by erikdsjostrom** [pynag/pynag#262]
What's the reason for not implementing rename for service objects?

**Comment by palli** [comment]
Yes this is working as intended. service has no "service_name" similar to what other objects have (host_name, hostgroup_name, etc).

Instead services have service_descriptions, which are not the same thing (for one they are not unique)

**Comment by palli** [comment]
I'll mark this as closed since this is working as intended but dont hesitate to reopen if you think there is a bug here.
